### ISSUE TITLE
Permission denied npm 5.7.1

### ISSUE THREAD

**Issue by poiromaniax** [ToddGreenfield/homebridge-onkyo#8]
Hi,

After doing a fresh install to npm 5.7.1, I am unable to install this plugin? (macos)

I am using sudo npm install -g homebridge-onkyo

code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/tillbaks/node-eiscp.git /Users/arielgeffen/.npm/_cacache/tmp/git-clone-e0f5adec
npm ERR! /Users/arielgeffen/.npm/_cacache/tmp/git-clone-e0f5adec/.git: Permission denied
npm ERR!

**Comment by poiromaniax** [comment]
Stupid me - issue was with npm permissions.

Fixed from here:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by tiny-e** [comment]
I can't get this to install for the life of me.  Fails with permission issues.  Other plugins install just fine.  No idea..

**Comment by ToddGreenfield** [comment]
Have you reviewed the doc in the link above regarding permission?

**Comment by tiny-e** [comment]
Yep... I did both (first one, then the other.. )  I've installed about 3 things with npm in my career, so my troubleshooting ability is kinda lacking here... I chmodded the folder /home/dave/.npm to 777... still throws the same error.

http://ecklund.us/paste/?c175130425cebfbb#YKyWNI/nu2n1/uli/VME9t43Lt4ZUtR4lH4s6zDdTwQ=
